// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "golang-family-tree/internal/domain/model"
	entity "golang-family-tree/internal/repository/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPersonService is a mock of PersonService interface.
type MockPersonService struct {
	ctrl     *gomock.Controller
	recorder *MockPersonServiceMockRecorder
}

// MockPersonServiceMockRecorder is the mock recorder for MockPersonService.
type MockPersonServiceMockRecorder struct {
	mock *MockPersonService
}

// NewMockPersonService creates a new mock instance.
func NewMockPersonService(ctrl *gomock.Controller) *MockPersonService {
	mock := &MockPersonService{ctrl: ctrl}
	mock.recorder = &MockPersonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonService) EXPECT() *MockPersonServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPersonService) Add(ctx context.Context, person model.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, person)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockPersonServiceMockRecorder) Add(ctx, person interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPersonService)(nil).Add), ctx, person)
}

// FindAll mocks base method.
func (m *MockPersonService) FindAll(ctx context.Context) ([]*entity.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*entity.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPersonServiceMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPersonService)(nil).FindAll), ctx)
}

// FindAscendantsById mocks base method.
func (m *MockPersonService) FindAscendantsById(ctx context.Context, id int64) ([]*model.Ascendancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAscendantsById", ctx, id)
	ret0, _ := ret[0].([]*model.Ascendancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAscendantsById indicates an expected call of FindAscendantsById.
func (mr *MockPersonServiceMockRecorder) FindAscendantsById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAscendantsById", reflect.TypeOf((*MockPersonService)(nil).FindAscendantsById), ctx, id)
}
